language:
    java

install:
    - sudo apt-get install jlint

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

after_script:
    jlint -source ./src/ ./target/classes/net/authorize/
    print_surefire_reports.sh
 
